### PR TITLE
Hydro Addressing and Catchment Characteristics Use Cases

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
Best laid plans... I came down with a bad stomach bug on Friday and left this half finished. Just got the first two use cases finished up and figured I'd get a PR in.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
Whoops! I just noticed that @mhweber was assigned the catchment charcteristics use cases. Feel free to mod / replace what I have in there. It's super minimalist.

**Comment by mhweber** [comment]
@dblodgett-usgs  - looks good to me at quick glance - will work with more this evening but will merge this PR for now

**Comment by mhweber** [comment]
Delete branch or leave?  I'll start using PRs for changes

**Comment by dblodgett-usgs** [comment]
Delete is fine.

From: Marc Weber ***@***.***>
Sent: Tuesday, May 30, 2023 9:23 AM
To: mhweber/ICRW8_Geospatial_Workshop ***@***.***>
Cc: Blodgett, David L ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [mhweber/ICRW8_Geospatial_Workshop] Hydro Addressing and Catchment Characteristics Use Cases (PR #3)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Delete branch or leave? I'll start using PRs for changes

-

**Pull request merged**
